export type AttentionSeverity = "critical" | "high" | "medium" | "low";

export type AttentionRule = {
  id: string;
  module:
    | "leads"
    | "clients"
    | "tasks"
    | "invoices"
    | "proposals"
    | "projects"
    | "inbox"
    | "calendar"
    | "tickets";
  title: string;
  severity: AttentionSeverity;
  signal: string;
  condition: string;
  recommendedAction: string;
  evidence: string[];
};

export const ATTENTION_RULES: AttentionRule[] = [
  {
    id: "leads_needs_follow_up",
    module: "leads",
    title: "Prospectos sin seguimiento",
    severity: "high",
    signal: "Lead abierto con baja actividad reciente o sin próxima acción.",
    condition:
      "Sin next_follow_up, o sin interacción reciente, o lead nuevo que ya lleva varios días sin avance.",
    recommendedAction: "Crear seguimiento, reasignar responsable o actualizar el estado.",
    evidence: ["status", "next_follow_up", "last_interaction_at", "updated_at", "created_at"],
  },
  {
    id: "leads_stale_5_days",
    module: "leads",
    title: "Prospectos fríos",
    severity: "high",
    signal: "Lead abierto con 5 días o más sin movimiento.",
    condition: "El lead no está cerrado y no registra interacción o actualización reciente.",
    recommendedAction: "Crear una próxima acción o confirmar si debe cerrarse.",
    evidence: ["status", "last_interaction_at", "updated_at"],
  },
  {
    id: "vip_client_stale",
    module: "clients",
    title: "Clientes VIP sin seguimiento",
    severity: "high",
    signal: "Cliente VIP con varios días sin actividad visible.",
    condition: "El cliente está en status VIP y no tiene actualización reciente.",
    recommendedAction: "Programar seguimiento o revisar oportunidades abiertas.",
    evidence: ["status", "updated_at", "account_manager"],
  },
  {
    id: "tasks_overdue",
    module: "tasks",
    title: "Tareas atrasadas",
    severity: "critical",
    signal: "Tarea activa con fecha vencida.",
    condition: "La tarea no está completada y due_date es menor que hoy.",
    recommendedAction: "Reasignar, completar o mover la fecha de entrega.",
    evidence: ["status", "due_date", "assigned_to", "related_lead_id", "related_project_id"],
  },
  {
    id: "tasks_due_today",
    module: "tasks",
    title: "Tareas de hoy",
    severity: "medium",
    signal: "Tarea activa con vencimiento en el día.",
    condition: "La tarea no está completada y due_date coincide con la fecha actual.",
    recommendedAction: "Revisar avance y cerrar hoy si es posible.",
    evidence: ["status", "due_date", "priority"],
  },
  {
    id: "tasks_upcoming",
    module: "tasks",
    title: "Tareas próximas",
    severity: "low",
    signal: "Tarea activa con vencimiento próximo.",
    condition: "La tarea no está completada y due_date está dentro de la ventana cercana.",
    recommendedAction: "Preparar el seguimiento antes de que venza.",
    evidence: ["status", "due_date", "priority"],
  },
  {
    id: "tasks_due_soon",
    module: "tasks",
    title: "Tareas por vencer",
    severity: "medium",
    signal: "Tarea activa con vencimiento dentro de 3 días.",
    condition: "La tarea no está completada y due_date cae en la ventana de 3 días.",
    recommendedAction: "Preparar el seguimiento antes de que venza.",
    evidence: ["status", "due_date", "priority"],
  },
  {
    id: "invoices_overdue",
    module: "invoices",
    title: "Facturas vencidas",
    severity: "critical",
    signal: "Factura abierta fuera de fecha de pago.",
    condition: "La factura no está pagada/cancelada y due_date ya pasó.",
    recommendedAction: "Confirmar cobro, enviar recordatorio o escalar seguimiento.",
    evidence: ["status", "due_date", "total", "client_id", "number"],
  },
  {
    id: "invoices_sent_pending_payment",
    module: "invoices",
    title: "Facturas enviadas sin cobro",
    severity: "high",
    signal: "Factura enviada que sigue pendiente de pago.",
    condition: "El estado está enviado y aún no está pagada.",
    recommendedAction: "Dar seguimiento comercial o financiero.",
    evidence: ["status", "due_date", "total", "client_id"],
  },
  {
    id: "invoices_due_today",
    module: "invoices",
    title: "Facturas vencen hoy",
    severity: "high",
    signal: "Factura abierta con fecha de pago para hoy.",
    condition: "La factura no está pagada/cancelada y due_date coincide con hoy.",
    recommendedAction: "Enviar recordatorio o confirmar pago hoy.",
    evidence: ["status", "due_date", "total", "client_id", "number"],
  },
  {
    id: "invoices_due_soon",
    module: "invoices",
    title: "Facturas por vencer",
    severity: "medium",
    signal: "Factura abierta con vencimiento dentro de 3 días.",
    condition: "La factura no está pagada/cancelada y due_date cae en la ventana de 3 días.",
    recommendedAction: "Preparar seguimiento preventivo de cobro.",
    evidence: ["status", "due_date", "total", "client_id", "number"],
  },
  {
    id: "pending_invoices",
    module: "invoices",
    title: "Cobros pendientes",
    severity: "high",
    signal: "Factura abierta, enviada o vencida pendiente de cobro.",
    condition: "Hay facturas abiertas que requieren seguimiento financiero.",
    recommendedAction: "Priorizar cobro y contacto con el cliente.",
    evidence: ["status", "due_date", "total", "client_id"],
  },
  {
    id: "proposals_pending_response",
    module: "proposals",
    title: "Propuestas pendientes",
    severity: "high",
    signal: "Propuesta enviada o vista sin respuesta reciente.",
    condition: "La propuesta sigue abierta y necesita empuje comercial.",
    recommendedAction: "Hacer seguimiento, responder dudas o actualizar el alcance.",
    evidence: ["status", "valid_until", "updated_at", "client_id", "number", "title"],
  },
  {
    id: "proposals_viewed_no_response",
    module: "proposals",
    title: "Propuestas vistas sin respuesta",
    severity: "high",
    signal: "Propuesta vista que sigue sin respuesta del cliente.",
    condition: "El estado es Viewed y no hay cambio reciente de respuesta.",
    recommendedAction: "Dar seguimiento comercial con contexto de la propuesta.",
    evidence: ["status", "sent_at", "updated_at", "client_id", "number"],
  },
  {
    id: "proposals_near_expiry",
    module: "proposals",
    title: "Propuestas por vencer",
    severity: "high",
    signal: "Propuesta con validez cercana a expirar.",
    condition: "valid_until está próxima o ya venció y la propuesta no está cerrada.",
    recommendedAction: "Revisar con el cliente antes de que caduque.",
    evidence: ["status", "valid_until", "updated_at"],
  },
  {
    id: "projects_risk",
    module: "projects",
    title: "Proyectos en riesgo",
    severity: "critical",
    signal: "Proyecto activo con entrega vencida o muy próxima.",
    condition: "El proyecto sigue activo y due_date ya pasó o está muy cerca.",
    recommendedAction: "Revisar avance, dependencias y bloqueos.",
    evidence: ["status", "due_date", "progress", "client_id", "product_id"],
  },
  {
    id: "inbox_open",
    module: "inbox",
    title: "Conversaciones sin responder",
    severity: "medium",
    signal: "Mensajes abiertos con intención comercial pendiente.",
    condition: "La conversación sigue abierta y tiene mensajes sin atender.",
    recommendedAction: "Responder, asignar o cerrar la conversación.",
    evidence: ["status", "unread_count", "last_message_at"],
  },
  {
    id: "wa_open",
    module: "inbox",
    title: "Bandeja pendiente",
    severity: "medium",
    signal: "Bandeja abierta con mensajes sin responder.",
    condition: "WhatsApp, Messenger o Email siguen abiertos.",
    recommendedAction: "Responder o reasignar la conversación.",
    evidence: ["status", "unread_count", "last_message_at"],
  },
  {
    id: "calendar_overdue",
    module: "calendar",
    title: "Eventos vencidos",
    severity: "medium",
    signal: "Evento programado que ya debería haberse ejecutado.",
    condition: "La fecha de inicio ya pasó y el evento no está completado.",
    recommendedAction: "Marcar como completado o reprogramar.",
    evidence: ["status", "start_at", "end_at", "all_day"],
  },
  {
    id: "calendar_meeting_missing_outcome",
    module: "calendar",
    title: "Reuniones sin resultado",
    severity: "medium",
    signal: "Reunión pasada sin outcome visible.",
    condition: "El evento de tipo meeting ya pasó y sigue programado/abierto.",
    recommendedAction: "Registrar resultado, crear tarea siguiente o reprogramar.",
    evidence: ["type", "status", "start_at", "description"],
  },
  {
    id: "calendar_upcoming",
    module: "calendar",
    title: "Eventos próximos",
    severity: "low",
    signal: "Evento programado dentro de la próxima ventana de atención.",
    condition: "La fecha de inicio está próxima y el evento sigue abierto.",
    recommendedAction: "Preparar o confirmar el evento.",
    evidence: ["status", "start_at", "end_at", "all_day"],
  },
  {
    id: "tickets_overdue",
    module: "tickets",
    title: "Tickets con riesgo",
    severity: "medium",
    signal: "Ticket abierto próximo o pasado de SLA.",
    condition: "La fecha de resolución está vencida o muy próxima.",
    recommendedAction: "Responder o escalar al área responsable.",
    evidence: ["status", "priority", "resolution_due_at", "updated_at"],
  },
  {
    id: "tickets_sla_due_soon",
    module: "tickets",
    title: "Tickets cerca del SLA",
    severity: "high",
    signal: "Ticket abierto con resolución próxima.",
    condition: "resolution_due_at está dentro de la ventana de 24 horas.",
    recommendedAction: "Responder o escalar antes de incumplir el SLA.",
    evidence: ["status", "priority", "resolution_due_at", "updated_at"],
  },
  {
    id: "client_product_renewal_due_soon",
    module: "clients",
    title: "Renovaciones próximas",
    severity: "medium",
    signal: "Producto o servicio de cliente próximo a renovar o terminar.",
    condition: "client_products.end_date cae dentro de la ventana de 30 días.",
    recommendedAction: "Contactar al cliente para confirmar renovación o continuidad.",
    evidence: ["client_id", "status", "end_date", "billing_type", "price"],
  },
];

export const ATTENTION_PRIORITY_ORDER: string[] = [
  "tasks_overdue",
  "invoices_overdue",
  "projects_risk",
  "tickets_sla_due_soon",
  "invoices_due_today",
  "leads_needs_follow_up",
  "leads_stale_5_days",
  "vip_client_stale",
  "proposals_viewed_no_response",
  "proposals_pending_response",
  "pending_invoices",
  "invoices_sent_pending_payment",
  "proposals_near_expiry",
  "invoices_due_soon",
  "inbox_open",
  "wa_open",
  "tasks_due_today",
  "tasks_due_soon",
  "calendar_overdue",
  "calendar_meeting_missing_outcome",
  "client_product_renewal_due_soon",
  "tasks_upcoming",
  "calendar_upcoming",
  "tickets_overdue",
];

export function getAttentionRuleById(ruleId: string) {
  return ATTENTION_RULES.find((rule) => rule.id === ruleId) || null;
}
