/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappWebRouteImport } from './routes/whatsapp-web'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SpreadsheetBuilderTestRouteImport } from './routes/spreadsheet-builder-test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InvoiceBuilderTestRouteImport } from './routes/invoice-builder-test'
import { Route as GoogleDriveCallbackRouteImport } from './routes/google-drive-callback'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DocumentBuilderTestRouteImport } from './routes/document-builder-test'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalPublicPublicTokenRouteImport } from './routes/proposal/public/$publicToken'
import { Route as InvoicePublicPublicTokenRouteImport } from './routes/invoice/public/$publicToken'

const WhatsappWebRoute = WhatsappWebRouteImport.update({
  id: '/whatsapp-web',
  path: '/whatsapp-web',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsheetBuilderTestRoute = SpreadsheetBuilderTestRouteImport.update({
  id: '/spreadsheet-builder-test',
  path: '/spreadsheet-builder-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceBuilderTestRoute = InvoiceBuilderTestRouteImport.update({
  id: '/invoice-builder-test',
  path: '/invoice-builder-test',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleDriveCallbackRoute = GoogleDriveCallbackRouteImport.update({
  id: '/google-drive-callback',
  path: '/google-drive-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentBuilderTestRoute = DocumentBuilderTestRouteImport.update({
  id: '/document-builder-test',
  path: '/document-builder-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalPublicPublicTokenRoute =
  ProposalPublicPublicTokenRouteImport.update({
    id: '/proposal/public/$publicToken',
    path: '/proposal/public/$publicToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvoicePublicPublicTokenRoute =
  InvoicePublicPublicTokenRouteImport.update({
    id: '/invoice/public/$publicToken',
    path: '/invoice/public/$publicToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/document-builder-test': typeof DocumentBuilderTestRoute
  '/email': typeof EmailRoute
  '/google-drive-callback': typeof GoogleDriveCallbackRoute
  '/invoice-builder-test': typeof InvoiceBuilderTestRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/spreadsheet-builder-test': typeof SpreadsheetBuilderTestRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/whatsapp': typeof WhatsappRoute
  '/whatsapp-web': typeof WhatsappWebRoute
  '/invoice/public/$publicToken': typeof InvoicePublicPublicTokenRoute
  '/proposal/public/$publicToken': typeof ProposalPublicPublicTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/document-builder-test': typeof DocumentBuilderTestRoute
  '/email': typeof EmailRoute
  '/google-drive-callback': typeof GoogleDriveCallbackRoute
  '/invoice-builder-test': typeof InvoiceBuilderTestRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/spreadsheet-builder-test': typeof SpreadsheetBuilderTestRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/whatsapp': typeof WhatsappRoute
  '/whatsapp-web': typeof WhatsappWebRoute
  '/invoice/public/$publicToken': typeof InvoicePublicPublicTokenRoute
  '/proposal/public/$publicToken': typeof ProposalPublicPublicTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/document-builder-test': typeof DocumentBuilderTestRoute
  '/email': typeof EmailRoute
  '/google-drive-callback': typeof GoogleDriveCallbackRoute
  '/invoice-builder-test': typeof InvoiceBuilderTestRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/spreadsheet-builder-test': typeof SpreadsheetBuilderTestRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/whatsapp': typeof WhatsappRoute
  '/whatsapp-web': typeof WhatsappWebRoute
  '/invoice/public/$publicToken': typeof InvoicePublicPublicTokenRoute
  '/proposal/public/$publicToken': typeof ProposalPublicPublicTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/automations'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/document-builder-test'
    | '/email'
    | '/google-drive-callback'
    | '/invoice-builder-test'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/projects'
    | '/proposals'
    | '/reports'
    | '/settings'
    | '/spreadsheet-builder-test'
    | '/tasks'
    | '/team'
    | '/whatsapp'
    | '/whatsapp-web'
    | '/invoice/public/$publicToken'
    | '/proposal/public/$publicToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/automations'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/document-builder-test'
    | '/email'
    | '/google-drive-callback'
    | '/invoice-builder-test'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/projects'
    | '/proposals'
    | '/reports'
    | '/settings'
    | '/spreadsheet-builder-test'
    | '/tasks'
    | '/team'
    | '/whatsapp'
    | '/whatsapp-web'
    | '/invoice/public/$publicToken'
    | '/proposal/public/$publicToken'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/automations'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/document-builder-test'
    | '/email'
    | '/google-drive-callback'
    | '/invoice-builder-test'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/projects'
    | '/proposals'
    | '/reports'
    | '/settings'
    | '/spreadsheet-builder-test'
    | '/tasks'
    | '/team'
    | '/whatsapp'
    | '/whatsapp-web'
    | '/invoice/public/$publicToken'
    | '/proposal/public/$publicToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AutomationsRoute: typeof AutomationsRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentBuilderTestRoute: typeof DocumentBuilderTestRoute
  EmailRoute: typeof EmailRoute
  GoogleDriveCallbackRoute: typeof GoogleDriveCallbackRoute
  InvoiceBuilderTestRoute: typeof InvoiceBuilderTestRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  ProposalsRoute: typeof ProposalsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SpreadsheetBuilderTestRoute: typeof SpreadsheetBuilderTestRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  WhatsappRoute: typeof WhatsappRoute
  WhatsappWebRoute: typeof WhatsappWebRoute
  InvoicePublicPublicTokenRoute: typeof InvoicePublicPublicTokenRoute
  ProposalPublicPublicTokenRoute: typeof ProposalPublicPublicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-web': {
      id: '/whatsapp-web'
      path: '/whatsapp-web'
      fullPath: '/whatsapp-web'
      preLoaderRoute: typeof WhatsappWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreadsheet-builder-test': {
      id: '/spreadsheet-builder-test'
      path: '/spreadsheet-builder-test'
      fullPath: '/spreadsheet-builder-test'
      preLoaderRoute: typeof SpreadsheetBuilderTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-builder-test': {
      id: '/invoice-builder-test'
      path: '/invoice-builder-test'
      fullPath: '/invoice-builder-test'
      preLoaderRoute: typeof InvoiceBuilderTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-drive-callback': {
      id: '/google-drive-callback'
      path: '/google-drive-callback'
      fullPath: '/google-drive-callback'
      preLoaderRoute: typeof GoogleDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-builder-test': {
      id: '/document-builder-test'
      path: '/document-builder-test'
      fullPath: '/document-builder-test'
      preLoaderRoute: typeof DocumentBuilderTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/public/$publicToken': {
      id: '/proposal/public/$publicToken'
      path: '/proposal/public/$publicToken'
      fullPath: '/proposal/public/$publicToken'
      preLoaderRoute: typeof ProposalPublicPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/public/$publicToken': {
      id: '/invoice/public/$publicToken'
      path: '/invoice/public/$publicToken'
      fullPath: '/invoice/public/$publicToken'
      preLoaderRoute: typeof InvoicePublicPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AutomationsRoute: AutomationsRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  DocumentBuilderTestRoute: DocumentBuilderTestRoute,
  EmailRoute: EmailRoute,
  GoogleDriveCallbackRoute: GoogleDriveCallbackRoute,
  InvoiceBuilderTestRoute: InvoiceBuilderTestRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  ProposalsRoute: ProposalsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SpreadsheetBuilderTestRoute: SpreadsheetBuilderTestRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  WhatsappRoute: WhatsappRoute,
  WhatsappWebRoute: WhatsappWebRoute,
  InvoicePublicPublicTokenRoute: InvoicePublicPublicTokenRoute,
  ProposalPublicPublicTokenRoute: ProposalPublicPublicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
