-- Corevix CRM — Contracts module foundation
-- Adds the core contracts entity, activity timeline table, RLS, and default role permissions.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.contracts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  contract_number bigint generated by default as identity,
  subject text not null,
  description text,
  status text not null default 'Draft' check (status in ('Draft', 'Active', 'Expired', 'Cancelled', 'Pending Signature')),
  contract_type text not null default 'Service Agreement',
  contract_value numeric(14,2),
  start_date date,
  end_date date,
  client_id uuid references public.clients(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  proposal_id uuid,
  deal_id uuid,
  assigned_to uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  signed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contracts_company_id_idx on public.contracts(company_id);
create index if not exists contracts_client_id_idx on public.contracts(client_id);
create index if not exists contracts_project_id_idx on public.contracts(project_id);
create index if not exists contracts_status_idx on public.contracts(status);
create index if not exists contracts_assigned_to_idx on public.contracts(assigned_to);
create index if not exists contracts_end_date_idx on public.contracts(end_date);

drop trigger if exists contracts_set_updated_at on public.contracts;
create trigger contracts_set_updated_at
before update on public.contracts
for each row execute function public.set_updated_at();

create table if not exists public.contract_activity_events (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  contract_id uuid not null references public.contracts(id) on delete cascade,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  action text not null,
  detail text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists contract_activity_events_company_id_idx on public.contract_activity_events(company_id);
create index if not exists contract_activity_events_contract_id_idx on public.contract_activity_events(contract_id);
create index if not exists contract_activity_events_created_at_idx on public.contract_activity_events(created_at desc);

alter table public.contracts enable row level security;
alter table public.contract_activity_events enable row level security;

drop policy if exists "Company members can view contracts" on public.contracts;
create policy "Company members can view contracts"
on public.contracts
for select
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.company_id = contracts.company_id
      and coalesce(p.is_active, true) = true
  )
);

drop policy if exists "Company members can create contracts" on public.contracts;
create policy "Company members can create contracts"
on public.contracts
for insert
with check (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.company_id = contracts.company_id
      and coalesce(p.is_active, true) = true
  )
);

drop policy if exists "Company members can update contracts" on public.contracts;
create policy "Company members can update contracts"
on public.contracts
for update
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.company_id = contracts.company_id
      and coalesce(p.is_active, true) = true
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.company_id = contracts.company_id
      and coalesce(p.is_active, true) = true
  )
);

drop policy if exists "Company members can delete contracts" on public.contracts;
create policy "Company members can delete contracts"
on public.contracts
for delete
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.company_id = contracts.company_id
      and coalesce(p.is_active, true) = true
  )
);

drop policy if exists "Company members can view contract activity" on public.contract_activity_events;
create policy "Company members can view contract activity"
on public.contract_activity_events
for select
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.company_id = contract_activity_events.company_id
      and coalesce(p.is_active, true) = true
  )
);

drop policy if exists "Company members can create contract activity" on public.contract_activity_events;
create policy "Company members can create contract activity"
on public.contract_activity_events
for insert
with check (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.company_id = contract_activity_events.company_id
      and coalesce(p.is_active, true) = true
  )
);

insert into public.permissions (company_id, module, role, can_view, can_create, can_edit, can_delete, can_assign)
select c.id, 'contracts', v.role::public.app_role, v.can_view, v.can_create, v.can_edit, v.can_delete, v.can_assign
from public.companies c
cross join (
  values
    ('admin', true, true, true, true, true),
    ('manager', true, true, true, true, true),
    ('sales_agent', true, true, true, false, false),
    ('viewer', true, false, false, false, false)
) as v(role, can_view, can_create, can_edit, can_delete, can_assign)
on conflict do nothing;
