create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity,
  company_id uuid not null references public.companies(id) on delete cascade,
  subject text not null,
  description text,
  status text not null default 'Open' check (status in ('Open', 'In Progress', 'Answered', 'On Hold', 'Closed')),
  priority text not null default 'Medium' check (priority in ('Low', 'Medium', 'High', 'Urgent')),
  department text not null default 'Support',
  service text,
  source text not null default 'manual' check (source in ('manual', 'email', 'whatsapp', 'portal', 'agent')),
  tags text[] not null default '{}',
  client_id uuid references public.clients(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  lead_id uuid references public.leads(id) on delete set null,
  assigned_to uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  first_response_due_at timestamptz,
  resolution_due_at timestamptz,
  last_reply_at timestamptz,
  closed_at timestamptz,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, ticket_number)
);

create table if not exists public.ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  author_type text not null default 'staff' check (author_type in ('staff', 'customer', 'system')),
  author_profile_id uuid references public.profiles(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete set null,
  body text not null,
  is_internal boolean not null default false,
  attachments jsonb not null default '[]',
  created_at timestamptz not null default now()
);

create table if not exists public.ticket_activity_events (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  event_type text not null,
  title text not null,
  description text,
  metadata jsonb not null default '{}',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists tickets_company_status_idx on public.tickets(company_id, status);
create index if not exists tickets_company_priority_idx on public.tickets(company_id, priority);
create index if not exists tickets_company_project_idx on public.tickets(company_id, project_id);
create index if not exists tickets_company_client_idx on public.tickets(company_id, client_id);
create index if not exists tickets_assigned_to_idx on public.tickets(assigned_to);
create index if not exists tickets_last_reply_idx on public.tickets(company_id, last_reply_at desc nulls last);
create index if not exists ticket_messages_ticket_idx on public.ticket_messages(ticket_id, created_at);
create index if not exists ticket_activity_ticket_idx on public.ticket_activity_events(ticket_id, created_at desc);

create or replace function public.set_ticket_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.status = 'Closed' and old.status is distinct from 'Closed' and new.closed_at is null then
    new.closed_at = now();
  elsif new.status is distinct from 'Closed' then
    new.closed_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists set_ticket_updated_at on public.tickets;
create trigger set_ticket_updated_at
before update on public.tickets
for each row execute function public.set_ticket_updated_at();

create or replace function public.sync_ticket_message_metadata()
returns trigger
language plpgsql
as $$
begin
  update public.tickets
  set last_reply_at = new.created_at,
      updated_at = now(),
      status = case
        when new.is_internal then status
        when new.author_type = 'customer' and status = 'Answered' then 'Open'
        when new.author_type = 'staff' and status in ('Open', 'In Progress') then 'Answered'
        else status
      end
  where id = new.ticket_id;

  insert into public.ticket_activity_events(ticket_id, company_id, event_type, title, description, created_by, metadata)
  values (
    new.ticket_id,
    new.company_id,
    case when new.is_internal then 'internal_note_added' else 'reply_added' end,
    case when new.is_internal then 'Internal note added' else 'Reply added' end,
    left(new.body, 240),
    new.author_profile_id,
    jsonb_build_object('message_id', new.id, 'author_type', new.author_type)
  );

  return new;
end;
$$;

drop trigger if exists sync_ticket_message_metadata on public.ticket_messages;
create trigger sync_ticket_message_metadata
after insert on public.ticket_messages
for each row execute function public.sync_ticket_message_metadata();

alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;
alter table public.ticket_activity_events enable row level security;

drop policy if exists tickets_company_select on public.tickets;
create policy tickets_company_select on public.tickets
for select using (company_id = public.get_current_company_id());

drop policy if exists tickets_company_insert on public.tickets;
create policy tickets_company_insert on public.tickets
for insert with check (company_id = public.get_current_company_id());

drop policy if exists tickets_company_update on public.tickets;
create policy tickets_company_update on public.tickets
for update using (company_id = public.get_current_company_id())
with check (company_id = public.get_current_company_id());

drop policy if exists tickets_company_delete on public.tickets;
create policy tickets_company_delete on public.tickets
for delete using (company_id = public.get_current_company_id());

drop policy if exists ticket_messages_company_select on public.ticket_messages;
create policy ticket_messages_company_select on public.ticket_messages
for select using (company_id = public.get_current_company_id());

drop policy if exists ticket_messages_company_insert on public.ticket_messages;
create policy ticket_messages_company_insert on public.ticket_messages
for insert with check (company_id = public.get_current_company_id());

drop policy if exists ticket_messages_company_update on public.ticket_messages;
create policy ticket_messages_company_update on public.ticket_messages
for update using (company_id = public.get_current_company_id())
with check (company_id = public.get_current_company_id());

drop policy if exists ticket_messages_company_delete on public.ticket_messages;
create policy ticket_messages_company_delete on public.ticket_messages
for delete using (company_id = public.get_current_company_id());

drop policy if exists ticket_activity_company_select on public.ticket_activity_events;
create policy ticket_activity_company_select on public.ticket_activity_events
for select using (company_id = public.get_current_company_id());

drop policy if exists ticket_activity_company_insert on public.ticket_activity_events;
create policy ticket_activity_company_insert on public.ticket_activity_events
for insert with check (company_id = public.get_current_company_id());

insert into public.permissions (company_id, module, role, can_view, can_create, can_edit, can_delete, can_assign)
select c.id, 'tickets', r.role, true, r.can_create, r.can_edit, r.can_delete, r.can_assign
from public.companies c
cross join (
  values
    ('super_admin'::public.app_role, true, true, true, true),
    ('admin'::public.app_role, true, true, true, true),
    ('manager'::public.app_role, true, true, true, true),
    ('sales_agent'::public.app_role, true, true, false, false),
    ('viewer'::public.app_role, false, false, false, false)
) as r(role, can_create, can_edit, can_delete, can_assign)
on conflict do nothing;
