-- Corevix CRM — Sales core sections
-- Estimates, payments, credit notes, subscriptions and expenses.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.estimates (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  number bigint generated by default as identity,
  title text not null default 'New Estimate',
  client_id uuid references public.clients(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  deal_id uuid references public.deals(id) on delete set null,
  subtotal numeric(14,2) not null default 0,
  tax numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  status text not null default 'Draft' check (status in ('Draft','Sent','Accepted','Declined','Expired','Converted')),
  date_issued date not null default current_date,
  expiry_date date,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  payment_number bigint generated by default as identity,
  invoice_id uuid references public.invoices(id) on delete set null,
  client_id uuid references public.clients(id) on delete set null,
  amount numeric(14,2) not null default 0,
  payment_date date not null default current_date,
  method text not null default 'Manual',
  status text not null default 'Completed' check (status in ('Pending','Completed','Failed','Refunded')),
  reference text,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_notes (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  credit_note_number bigint generated by default as identity,
  invoice_id uuid references public.invoices(id) on delete set null,
  client_id uuid references public.clients(id) on delete set null,
  amount numeric(14,2) not null default 0,
  status text not null default 'Draft' check (status in ('Draft','Issued','Applied','Cancelled')),
  date_issued date not null default current_date,
  reason text,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  client_id uuid references public.clients(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  amount numeric(14,2) not null default 0,
  billing_cycle text not null default 'Monthly' check (billing_cycle in ('Weekly','Monthly','Quarterly','Yearly')),
  status text not null default 'Active' check (status in ('Trial','Active','Paused','Cancelled','Expired')),
  start_date date not null default current_date,
  next_billing_date date,
  end_date date,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  title text not null,
  vendor text,
  category text not null default 'General',
  amount numeric(14,2) not null default 0,
  status text not null default 'Pending' check (status in ('Pending','Approved','Paid','Rejected')),
  expense_date date not null default current_date,
  project_id uuid references public.projects(id) on delete set null,
  client_id uuid references public.clients(id) on delete set null,
  receipt_url text,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists estimates_company_id_idx on public.estimates(company_id);
create index if not exists estimates_client_id_idx on public.estimates(client_id);
create index if not exists payments_company_id_idx on public.payments(company_id);
create index if not exists payments_invoice_id_idx on public.payments(invoice_id);
create index if not exists credit_notes_company_id_idx on public.credit_notes(company_id);
create index if not exists subscriptions_company_id_idx on public.subscriptions(company_id);
create index if not exists expenses_company_id_idx on public.expenses(company_id);

alter table public.estimates enable row level security;
alter table public.payments enable row level security;
alter table public.credit_notes enable row level security;
alter table public.subscriptions enable row level security;
alter table public.expenses enable row level security;

do $$
declare t text;
begin
  foreach t in array array['estimates','payments','credit_notes','subscriptions','expenses'] loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', t, t);
    execute format('create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t);
    execute format('drop policy if exists "Company members can view %s" on public.%I', t, t);
    execute format('create policy "Company members can view %s" on public.%I for select using (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.company_id = %I.company_id and coalesce(p.is_active,true)=true))', t, t, t);
    execute format('drop policy if exists "Company members can insert %s" on public.%I', t, t);
    execute format('create policy "Company members can insert %s" on public.%I for insert with check (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.company_id = %I.company_id and coalesce(p.is_active,true)=true))', t, t, t);
    execute format('drop policy if exists "Company members can update %s" on public.%I', t, t);
    execute format('create policy "Company members can update %s" on public.%I for update using (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.company_id = %I.company_id and coalesce(p.is_active,true)=true)) with check (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.company_id = %I.company_id and coalesce(p.is_active,true)=true))', t, t, t, t);
    execute format('drop policy if exists "Company members can delete %s" on public.%I', t, t);
    execute format('create policy "Company members can delete %s" on public.%I for delete using (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.company_id = %I.company_id and coalesce(p.is_active,true)=true))', t, t, t);
  end loop;
end $$;

insert into public.permissions (company_id, module, role, can_view, can_create, can_edit, can_delete, can_assign)
select c.id, v.module, v.role::public.app_role, v.can_view, v.can_create, v.can_edit, v.can_delete, false
from public.companies c
cross join (values
  ('estimates','admin',true,true,true,true),('estimates','manager',true,true,true,true),('estimates','sales_agent',true,true,true,false),('estimates','viewer',true,false,false,false),
  ('payments','admin',true,true,true,true),('payments','manager',true,true,true,true),('payments','sales_agent',true,true,true,false),('payments','viewer',true,false,false,false),
  ('credit_notes','admin',true,true,true,true),('credit_notes','manager',true,true,true,true),('credit_notes','sales_agent',true,true,true,false),('credit_notes','viewer',true,false,false,false),
  ('subscriptions','admin',true,true,true,true),('subscriptions','manager',true,true,true,true),('subscriptions','sales_agent',true,true,true,false),('subscriptions','viewer',true,false,false,false),
  ('expenses','admin',true,true,true,true),('expenses','manager',true,true,true,true),('expenses','sales_agent',true,true,true,false),('expenses','viewer',true,false,false,false)
) as v(module, role, can_view, can_create, can_edit, can_delete)
on conflict (company_id, module, role) do nothing;
